project: "naiss2024-22-540"
outdir: "/proj/applied_bioinformatics/users/x_amrbi/nf_output"
input_read_pairs: "/proj/applied_bioinformatics/users/x_amrbi/data/sra_fastqc/*{1,2}.fastq.gz"
bowtie2_db: "/proj/applied_bioinformatics/users/x_amrbi/data/bowtie2_DBs/SC2_bowtie2_DB*"
